dist: trusty
sudo: required
before_install:
language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- python setup.py install
- pip install coveralls
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- coverage run --source=wrangle ./test_script.py
after_success: coveralls
deploy:
  provider: pypi
  user: mikkokotila
  password:
    secure: puck8pvLknVtyMb51AWTmez1SYTWkEw8OYOvsiq9zTq2ufbP3JhW/CavRRxnqEPz+IdpJYb2mRyVFEv0kj/a+bn+7dSSe+QxZ5tLlbDuw8/rT9Iw8Mx11gajo5Vl/3R/VWdmbO7G6ndoSuJRHIDo80F7TL9Yp1ngriqouG+FGMfmEnwu+w0HlW64dzrdnOa9yy8gmHRDeEQa8i/Xd65g8VG1jhBIE6at0dK6XZmWCcpY73yZo2nPDIxuQp7dU+chmfupzNSDRuad+O/MY+ZeorEHiKg+WOYiks6EvLkKhad3gjXKTOCnH7ZgRboOKk7hKDinK29bTAgtgjoLlPwStXgrsy+TsXlJyHm9kjOE+lXbGVOZIL9yYXHGWgMOcN5/o5jPoU6hHtwDCVoQSA3zBMApr168ZHncS8k5E1J2UkfZwbKTAS7GQ6KnpcSYsGoyvr6kye31gOjL/ahi7eo5u0POekj/pf3elTiCdc7YqppLKPArUS3b5Dm1GZO5md8OE7mNyw5/D+us+HShzwpKSlNj/LIdIwKEKoGNQLcdgh49WLZuyOcwzwCNUvvCmlhxkwvbA/ds3o9gGOWuNJs2UNdT26au330eZTzZL6FQ/O2tv9IsrX7XOkZyyjpHUnIGY9be3/tLDKnCmlzMLeVztl2T9fh7OkpfXYtKkOBjUgQ=
  on:
    branch: production
